let currentUser=null,stampTargetCheckbox=null,deferredPrompt=null,teacherClasses=[],selectedTeacherClassId=null;
const TEACHER_PIN='250084';
const VIRTUES=['건강','활력','기쁨','즐거움','격려','경청','공감','나눔','배려','사랑','신뢰','예의','우정','정의','존중','진정성','책임','친절','협력','지혜','창의성','탁월함','호기심','결단','겸손','긍정','끈기','노력','도전','성찰','실천','열정','용기','자신감','정직','감동','감사','깨달음','꿈','몰입','보람','창조','평화','행복','희망'];
const TASKS={
stage1:[['task1-1','1단계 : 한 손 위로 던지고 받기(오른손)'],['task1-2','2단계 : 한 손 위로 던지고 받기(왼손)'],['task1-3','3단계 : 한 손 던지고 반대 손 받기(오른손 → 왼손)'],['task1-4','4단계 : 한 손 던지고 반대 손 받기(왼손 → 오른손)'],['task1-5','5단계 : 한 손 던지고 반대 손 받기 연속',true]],
stage2:[['task2-1','6단계 : 양손에 공을 쥔 채 오른손 던지고 왼손 받기'],['task2-2','7단계 : 양손에 공을 쥔 채 왼손 던지고 오른손 받기'],['task2-3','8단계 : 양손 번갈아 위로 던지고 받기'],['task2-4','9단계 : 양손 동시에 위로 던지고 받기'],['task2-5','10단계 : 양손 동시에 교차하여 던지고 받기',true],['task2-6','11단계 : 오른손 왼손 순차적으로 던지고 받기 (오왼받받)'],['task2-7','12단계 : 왼손 오른손 순차적으로 던지고 받기 (왼오받받)'],['task2-8','13단계 : 양손 번갈아 순차적으로 던지고 받기 8박자',true]],
stage3:[['task3-1','14단계 : 오른손 2개 쥔 채로 던지고 던지고 던지고'],['task3-2','15단계 : 왼손 2개 쥔 채로 던지고 던지고 던지고'],['task3-3','16단계 : 오른손 2개 쥔 채로 던던받받',true],['task3-4','17단계 : 왼손 2개 쥔 채로 던던받받',true],['task3-5','18단계 : 오른손 2개 쥔 채로 던던던받'],['task3-6','19단계 : 왼손 2개 쥔 채로 던던던받'],['task3-7','20단계 : 오른손 2개 쥔 채로 던던던받받',true],['task3-8','21단계 : 왼손 2개 쥔 채로 던던던받받',true],['task3-9','22단계 : 오른손 2개 쥔 채로 4번 던지기'],['task3-10','23단계 : 왼손 2개 쥔 채로 4번 던지기'],['task3-11','24단계 : 오른손 2개 쥔 채로 4번 던지고 받기',true],['task3-12','25단계 : 왼손 2개 쥔 채로 4번 던지고 받기',true],['task3-13','26단계 : 오른손 2개 쥔 채로 5번 던지기'],['task3-14','27단계 : 왼손 2개 쥔 채로 5번 던지기'],['task3-15','28단계 : 오른손 2개 쥔 채로 5번 던지고 받기',true],['task3-16','29단계 : 왼손 2개 쥔 채로 5번 던지고 받기',true],['task3-17','30단계(최종) : 연속 저글링 개인 신기록 세우기']]
};
const STAGE_TITLES={stage1:'공 1개와 친해지기',stage2:'공 2개 다루기',stage3:'공 3개 도전!!'};
function showView(id){['login-view','student-view','teacher-view'].forEach(x=>document.getElementById(x).classList.add('hidden'));document.getElementById(id).classList.remove('hidden')}
async function handleLogin(){const info={classCode:$('class-code').value.trim(),grade:document.getElementById('grade').value.trim(),classNum:document.getElementById('classNum').value.trim(),number:document.getElementById('number').value.trim(),name:document.getElementById('name').value.trim(),pin:$('student-pin').value.trim()};if(Object.values(info).some(v=>!v))return alert('학급 코드, 학년, 반, 번호, 이름, 개인 PIN을 모두 입력해주세요.');if(!/^\d{6}$/.test(info.pin))return alert('개인 PIN은 숫자 6자리로 입력해주세요.');try{currentUser=await getOrCreateStudent(info);renderStudentView(currentUser);showView('student-view')}catch(err){console.error(err);alert('학생 로그인 중 오류가 발생했습니다: '+(err?.message||err))}}
function renderStudentView(s){studentInfo.textContent=`${s.grade}학년 ${s.classNum}반 ${s.number}번 ${s.name}`;renderChecklist(s);renderVirtueSelection(s);renderGrowthDashboard(s)}
function renderChecklist(s){checklistContainer.innerHTML='';Object.keys(TASKS).forEach(stage=>{const done=TASKS[stage].every(t=>s.tasks?.[stage]?.[t[0]]);const div=document.createElement('div');div.className='stage';div.innerHTML=`${done?'<span class="badge">🎉 완료!</span>':''}<h3>${STAGE_TITLES[stage]}</h3>${TASKS[stage].map(t=>`<label class="task"><input type="checkbox" data-stage="${stage}" data-task="${t[0]}" data-stamp="${!!t[2]}" ${s.tasks?.[stage]?.[t[0]]?'checked':''}><span>${t[1]} ${t[2]?'<span class="stamp">교사 확인</span>':''}</span></label>`).join('')}`;checklistContainer.appendChild(div)});document.querySelectorAll('.task input').forEach(cb=>cb.onchange=()=>{if(cb.dataset.stamp==='true'&&cb.checked){cb.checked=false;stampTargetCheckbox=cb;passwordModalTitle.textContent='교사 확인';passwordModal.classList.remove('hidden');return}saveCheckbox(cb)})}
async function saveCheckbox(cb){const st=cb.dataset.stage,id=cb.dataset.task;currentUser.tasks[st]||={};currentUser.tasks[st][id]=cb.checked;await saveStudentData(currentUser);renderChecklist(currentUser)}

const TIERS=[
{name:'UNRANKED',min:0,next:5,emoji:'🌱',cls:'tier-unranked',message:'첫 기록을 남기고 성장 여정을 시작하세요!'},
{name:'SILVER',min:5,next:10,emoji:'🥈',cls:'tier-silver',message:'기본기가 쌓이고 있어요. 10회를 향해 도전!'},
{name:'GOLD',min:10,next:15,emoji:'🥇',cls:'tier-gold',message:'두 자릿수 돌파! 안정적인 리듬을 만들어보세요.'},
{name:'PLATINUM',min:15,next:20,emoji:'⚡',cls:'tier-platinum',message:'멋진 집중력! 이제 20회 벽을 넘어보세요.'},
{name:'DIAMOND',min:20,next:25,emoji:'💎',cls:'tier-diamond',message:'상위권 실력! 작은 실수까지 줄여볼 시간이에요.'},
{name:'MASTER',min:25,next:30,emoji:'🔥',cls:'tier-master',message:'마스터의 영역입니다. 챌린저까지 단 5회!'},
{name:'CHALLENGER',min:30,next:null,emoji:'👑',cls:'tier-challenger',message:'최고 티어 달성! 이제 나만의 최고 기록을 계속 경신하세요.'}
];
function getTier(record){let tier=TIERS[0];TIERS.forEach(t=>{if(record>=t.min)tier=t});return tier}
function renderGrowthChart(records){
const chart=$('growth-chart');
if(!records.length){chart.innerHTML='<div class="chart-empty"><div class="chart-empty-icon">📉</div><b>아직 기록이 없어요.</b><span>첫 기록을 저장하면 성장 그래프가 시작됩니다.</span></div>';return}
const w=720,h=260,pL=48,pR=22,pT=24,pB=42,maxVal=Math.max(10,...records),yMax=Math.ceil(maxVal/5)*5,innerW=w-pL-pR,innerH=h-pT-pB;
const x=i=>pL+(records.length===1?innerW/2:(i/(records.length-1))*innerW),y=v=>pT+innerH-(v/yMax)*innerH;
const points=records.map((v,i)=>`${x(i)},${y(v)}`).join(' ');
let grid='';
for(let i=0;i<=4;i++){const val=Math.round(yMax*(4-i)/4),gy=pT+(innerH*i/4);grid+=`<line x1="${pL}" y1="${gy}" x2="${w-pR}" y2="${gy}" class="chart-gridline"/><text x="${pL-10}" y="${gy+4}" text-anchor="end" class="chart-axis">${val}</text>`}
let dots='';
records.forEach((v,i)=>{dots+=`<circle cx="${x(i)}" cy="${y(v)}" r="5.5" class="chart-dot"/><text x="${x(i)}" y="${y(v)-12}" text-anchor="middle" class="chart-value">${v}</text><text x="${x(i)}" y="${h-14}" text-anchor="middle" class="chart-axis">${i+1}회</text>`});
const areaPoints=`${pL},${pT+innerH} ${points} ${x(records.length-1)},${pT+innerH}`;
chart.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="저글링 회차별 성장 그래프"><defs><linearGradient id="growthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#3b82f6" stop-opacity=".28"/><stop offset="100%" stop-color="#3b82f6" stop-opacity=".02"/></linearGradient></defs>${grid}<polygon points="${areaPoints}" fill="url(#growthFill)"/><polyline points="${points}" class="chart-line"/>${dots}</svg>`;
}
function renderGrowthDashboard(s){
const records=(s.cascadeRecords||[]).map(Number).filter(v=>Number.isFinite(v));
$('record-table-body').innerHTML=`<tr><td>기록</td>${Array.from({length:10},(_,i)=>`<td>${records[i]??'-'}</td>`).join('')}</tr>`;
const best=records.length?Math.max(...records):0,avg=records.length?Math.round((records.reduce((a,b)=>a+b,0)/records.length)*10)/10:0,latest=records.length?records[records.length-1]:0,growth=records.length>1?latest-records[0]:0;
$('stat-best').textContent=best;$('stat-average').textContent=avg;$('stat-latest').textContent=latest;$('stat-growth').textContent=(growth>0?'+':'')+growth;
const tier=getTier(best),card=$('tier-card');card.className=`tier-card ${tier.cls}`;$('tier-emblem').textContent=tier.emoji;$('tier-name').textContent=tier.name;$('tier-message').textContent=tier.message;
if(tier.next){const progress=Math.max(0,Math.min(100,((best-tier.min)/(tier.next-tier.min))*100));$('tier-progress-bar').style.width=progress+'%';$('tier-progress-text').textContent=`다음 티어까지 ${Math.max(0,tier.next-best)}회 남았습니다.`}
else{$('tier-progress-bar').style.width='100%';$('tier-progress-text').textContent='최고 티어 달성! 개인 최고 기록에 계속 도전하세요.'}
if(records.length===0)$('growth-summary').textContent='기록을 입력하면 그래프가 나타납니다.';
else if(records.length===1)$('growth-summary').textContent='첫 기록이 저장되었습니다!';
else if(growth>0)$('growth-summary').textContent=`첫 기록보다 ${growth}회 성장했어요!`;
else if(growth===0)$('growth-summary').textContent='첫 기록과 같은 수준을 유지하고 있어요.';
else $('growth-summary').textContent='괜찮아요. 다음 기록에서 다시 도전해보세요!';
renderGrowthChart(records)
}
async function saveRecordFn(){const n=parseInt(recordInput.value);if(Number.isNaN(n)||n<0)return alert('올바른 숫자를 입력해주세요.');currentUser.cascadeRecords||=[];if(currentUser.cascadeRecords.length>=10)return alert('10회차 기록을 모두 완료했습니다.');currentUser.cascadeRecords.push(n);await saveStudentData(currentUser);recordInput.value='';renderGrowthDashboard(currentUser)}
function renderVirtueSelection(s){const sel=s.selectedVirtues||[];if(s.finalVirtue){multiVirtueContainer.classList.add('hidden');finalVirtueContainer.classList.add('hidden');aiFeedbackContainer.classList.remove('hidden');aiFeedback.innerHTML=`<b>나의 핵심가치: ${s.finalVirtue}</b><p>${s.aiFeedback||''}</p>`;return}aiFeedbackContainer.classList.add('hidden');if(sel.length===3&&s.virtueReason){multiVirtueContainer.classList.add('hidden');finalVirtueContainer.classList.remove('hidden');finalVirtueSelectionGrid.innerHTML=sel.map(v=>`<button class="virtue final-choice">${v}</button>`).join('');document.querySelectorAll('.final-choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.final-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});return}multiVirtueContainer.classList.remove('hidden');finalVirtueContainer.classList.add('hidden');virtueSelectionGrid.innerHTML=VIRTUES.map(v=>`<button class="virtue ${sel.includes(v)?'selected':''}">${v}</button>`).join('');virtueReason.value=s.virtueReason||'';document.querySelectorAll('#virtue-selection-grid .virtue').forEach(b=>b.onclick=()=>{const selected=document.querySelectorAll('#virtue-selection-grid .selected');if(b.classList.contains('selected'))b.classList.remove('selected');else if(selected.length<3)b.classList.add('selected');else alert('가치는 3개까지만 선택할 수 있습니다.')})}
async function saveMultiVirtuesFn(){const s=[...document.querySelectorAll('#virtue-selection-grid .selected')].map(b=>b.textContent),reason=virtueReason.value.trim();if(s.length!==3)return alert('가치 3가지를 선택해주세요.');if(!reason)return alert('이유를 적어주세요.');currentUser.selectedVirtues=s;currentUser.virtueReason=reason;await saveStudentData(currentUser);renderVirtueSelection(currentUser)}
async function saveFinalVirtueFn(){const b=document.querySelector('.final-choice.selected');if(!b)return alert('가치 1가지를 선택해주세요.');currentUser.finalVirtue=b.textContent;currentUser.aiFeedback=`${currentUser.name}님, '${b.textContent}'이라는 가치를 마음에 새기고 연습한다면 저글링 실력뿐 아니라 마음도 함께 성장할 거예요. 응원합니다!`;await saveStudentData(currentUser);renderVirtueSelection(currentUser)}
async function renderTeacherDashboard(){teacherClasses=await getTeacherClasses();$('teacher-account').textContent=`${auth.currentUser.displayName||'선생님'} (${auth.currentUser.email}) · 내 학급만 안전하게 표시됩니다.`;if(!teacherClasses.some(c=>c.id===selectedTeacherClassId))selectedTeacherClassId=teacherClasses[0]?.id||null;$('class-list').innerHTML=teacherClasses.length?teacherClasses.map(c=>`<button class="class-pill ${c.id===selectedTeacherClassId?'active':''}" data-class-id="${c.id}">${c.name}<small>코드 ${c.code}</small></button>`).join(''):'<p class="muted">아직 만든 학급이 없습니다. 위에서 첫 학급을 만들어주세요.</p>';document.querySelectorAll('.class-pill').forEach(b=>b.onclick=()=>selectTeacherClass(b.dataset.classId));showView('teacher-view');await selectTeacherClass(selectedTeacherClassId)}
async function selectTeacherClass(classId){selectedTeacherClassId=classId;document.querySelectorAll('.class-pill').forEach(b=>b.classList.toggle('active',b.dataset.classId===classId));const teacherClass=teacherClasses.find(c=>c.id===classId);if(!teacherClass){$('class-share-panel').classList.add('hidden');dashboardBody.innerHTML='<tr><td colspan="7">학급을 만들거나 선택해주세요.</td></tr>';return}$('class-share-panel').classList.remove('hidden');$('student-link').value=`${location.origin}${location.pathname}?class=${teacherClass.code}`;const list=await getAllStudentData(classId);list.sort((a,b)=>`${a.grade}-${a.classNum}-${String(a.number).padStart(2,'0')}`.localeCompare(`${b.grade}-${b.classNum}-${String(b.number).padStart(2,'0')}`));dashboardBody.innerHTML=list.length?list.map(s=>{const counts=['stage1','stage2','stage3'].map(st=>TASKS[st].filter(t=>s.tasks?.[st]?.[t[0]]).length+'/'+TASKS[st].length);const best=s.cascadeRecords?.length?Math.max(...s.cascadeRecords):0;return `<tr><td>${s.grade}-${s.classNum}-${s.number}-${s.name}</td><td>${counts[0]}</td><td>${counts[1]}</td><td>${counts[2]}</td><td><b>${best}</b></td><td>${s.finalVirtue||'-'}</td><td><button class="btn red del" data-id="${s.studentId}" data-name="${s.name}">삭제</button></td></tr>`}).join(''):'<tr><td colspan="7">이 학급에 등록된 학생이 없습니다.</td></tr>';document.querySelectorAll('.del').forEach(b=>b.onclick=()=>{studentToDeleteName.textContent=b.dataset.name;deleteConfirmModal.classList.remove('hidden');deleteConfirmButton.onclick=async()=>{await deleteStudent(selectedTeacherClassId,b.dataset.id);deleteConfirmModal.classList.add('hidden');selectTeacherClass(selectedTeacherClassId)}})}
function submitPassword(){if(passwordInput.value!==TEACHER_PIN){passwordInput.value='';return alert('비밀번호가 틀렸습니다.')}if(stampTargetCheckbox){stampTargetCheckbox.checked=true;const cb=stampTargetCheckbox;stampTargetCheckbox=null;passwordModal.classList.add('hidden');saveCheckbox(cb)}else{passwordModal.classList.add('hidden');renderTeacherDashboard()}passwordInput.value=''}
const $=id=>document.getElementById(id);['grade','classNum','number','name','studentInfo','checklistContainer','recordTableBody','recordInput','multiVirtueContainer','finalVirtueContainer','aiFeedbackContainer','aiFeedback','virtueSelectionGrid','virtueReason','finalVirtueSelectionGrid','dashboardBody','passwordModal','passwordModalTitle','passwordInput','deleteConfirmModal','studentToDeleteName','deleteConfirmButton'].forEach(id=>window[id]=$(id.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())));
$('start-button').onclick=handleLogin;$('logout-button').onclick=()=>{currentUser=null;showView('login-view')};$('teacher-mode-button').onclick=async()=>{try{await signInTeacher();await renderTeacherDashboard()}catch(err){console.error(err);alert('교사 로그인에 실패했습니다: '+(err?.message||err))}};$('student-mode-button').onclick=async()=>{if(auth.currentUser&&!auth.currentUser.isAnonymous)await auth.signOut();showView('login-view')};$('create-class-button').onclick=async()=>{const data={name:$('new-class-name').value.trim(),grade:$('new-class-grade').value.trim(),classNum:$('new-class-num').value.trim()};if(Object.values(data).some(v=>!v))return alert('학급 이름, 학년, 반을 모두 입력해주세요.');try{const made=await createTeacherClass(data);selectedTeacherClassId=made.id;['new-class-name','new-class-grade','new-class-num'].forEach(id=>$(id).value='');await renderTeacherDashboard();alert(`학급 코드 ${made.code}가 만들어졌습니다.`)}catch(err){console.error(err);alert('학급 생성에 실패했습니다: '+err.message)}};$('copy-link-button').onclick=async()=>{try{await navigator.clipboard.writeText($('student-link').value);alert('학생 참여 주소를 복사했습니다.')}catch{ $('student-link').select();document.execCommand('copy');alert('학생 참여 주소를 복사했습니다.')}};$('save-record-button').onclick=saveRecordFn;$('save-virtue-button').onclick=saveMultiVirtuesFn;$('save-final-virtue-button').onclick=saveFinalVirtueFn;$('password-submit').onclick=submitPassword;$('password-cancel').onclick=()=>passwordModal.classList.add('hidden');$('delete-cancel-button').onclick=()=>deleteConfirmModal.classList.add('hidden');passwordInput.onkeyup=e=>{if(e.key==='Enter')submitPassword()};function openStudentTab(n){[1,2,3].forEach(i=>{$('tab-step'+i).classList.toggle('active',i===n);$('step'+i+'-content').classList.toggle('hidden',i!==n)});if(n===3&&currentUser)renderGrowthDashboard(currentUser)}
$('tab-step1').onclick=()=>openStudentTab(1);$('tab-step2').onclick=()=>openStudentTab(2);$('tab-step3').onclick=()=>openStudentTab(3);$('csv-button').onclick=async()=>{try{await exportClassCsv(selectedTeacherClassId)}catch(err){alert(err.message)}};$('backup-button').onclick=exportAllData;$('restore-input').onchange=async e=>{if(!e.target.files[0])return;try{const n=await importAllData(e.target.files[0]);alert(`${n}명의 데이터를 복원했습니다.`);renderTeacherDashboard()}catch(err){alert(err.message)}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('install-button').classList.remove('hidden')});$('install-button').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('install-button').classList.add('hidden')};if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())); if('caches' in window){caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)));}}
const initialClassCode=new URLSearchParams(location.search).get('class');if(initialClassCode)$('class-code').value=initialClassCode.toUpperCase();showView('login-view');
